version: '2'
services:
  application:
    container_name: "asset_registry"
    build: .
    ports:
     - "80:3000"
    networks:
     - default
  database:
    image: "mongo"
    container_name: "mongodb"
    ports:
     - "27017:27017"
    networks:
     - default

networks:
  default:
    driver: bridge
